# Include SSH configuration files for all Lima instances
Include ~/.lima/*/ssh.config

# Enable agent forwarding for all Lima instances
#
# In theory, you can set this up in the Lima configuration and it will write it to the generated
# instance SSH config even in plain mode, but it emits a warning so this is a cleaner way.
Host lima-*
  ForwardAgent yes
